services:

  nginx_http:
    image: nginx:latest
    container_name: nginx_http
    ports:
      - 80:80
    volumes:
      - ${WORK_DIR}/runtime/nginx_http/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/www:/var/www/certbot/:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ${WORK_DIR}/runtime/nginx/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${WORK_DIR}/runtime/certbot/www/:/var/www/certbot/:rw
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/letsencrypt/:rw
