services:
  auto-deploy:
    build:
      context: .
      args:
        COMMIT_HASH: ${COMMIT_HASH}
    image: ivannglivelyimpact/auto-deploy:${TAG}
    container_name: auto-deploy
    entrypoint: tail
    command: -f /dev/null
    volumes:
      - ./env:/app/env
    extra_hosts:
      - "host.docker.internal:host-gateway"
