services:
  # Nginx HTTP
  nginx_http:
    image: nginx:latest
    container_name: nginx_http
    ports:
      - 80:80
    volumes:
      - ${WORK_DIR}/config/nginx_http/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/www:/var/www/certbot/:ro

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ${WORK_DIR}/config/nginx/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/nginx/ssl/:ro

  # Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${WORK_DIR}/runtime/certbot/www/:/var/www/certbot/:rw
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/letsencrypt/:rw

  # Keycloak
  # keycloak:
  #   container_name: keycloak
  #   image: jboss/keycloak:latest

  #   environment:
  #     PROXY_ADDRESS_FORWARDING: 'true'
  #     KEYCLOAK_FRONTEND_URL: https://alexwbt.com/auth/
  #     DB_VENDOR: postgres
  #     DB_ADDR: ${KEYCLOAK_DB_ADDR}
  #     DB_PORT: ${KEYCLOAK_DB_PORT}
  #     DB_SCHEMA: keycloak
  #     DB_DATABASE: keycloak
  #     DB_USER: keycloak
  #     DB_PASSWORD_FILE: /env/secret/db_password_file
  #   ports:
  #     - ${KEYCLOAK_TCP_PORT}:${KEYCLOAK_TCP_PORT}

  #   volumes:
  #     - ${PWD}/env/secret/keycloak-db_password_file:/env/secret/db_password_file
  #     - ${PWD}/volumes/keycloak/discovery:/opt/jboss/tools/cli/jgroups/discovery

  #   entrypoint: /opt/jboss/tools/docker-entrypoint.sh
