version: "3"
services:
  # Nginx HTTP
  nginx_http:
    restart: always
    image: nginx:latest
    container_name: nginx_http
    ports:
      - 80:80
    volumes:
      - ${WORK_DIR}/config/nginx_http/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/www:/var/www/certbot/:ro

  # Nginx
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ${WORK_DIR}/config/nginx/conf/:/etc/nginx/conf.d/:ro
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/nginx/ssl/:ro

  # Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${WORK_DIR}/runtime/certbot/www/:/var/www/certbot/:rw
      - ${WORK_DIR}/runtime/certbot/conf/:/etc/letsencrypt/:rw

  # alexwbt
  alexwbt:
    restart: always
    image: alexwbt:latest
    container_name: alexwbt

  # alexwbt-api
  alexwbt-api:
    restart: always
    image: alexwbt-api:latest
    container_name: alexwbt-api

  # MySql
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-data:
