
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;


events {
  worker_connections 1024;
}


http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;

  sendfile on;

  keepalive_timeout 65;

  server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    fastcgi_read_timeout 1h;
    proxy_read_timeout 1h;

    server_name {{ALEXWBT_DOMAIN_NAME}};

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Ssl on;

    ssl_certificate /etc/nginx/ssl/live/{{ALEXWBT_DOMAIN_NAME}}/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/{{ALEXWBT_DOMAIN_NAME}}/privkey.pem;

    location /repository/activity/ {
      proxy_pass http://code-activity-server:3000/repository/activity/;
    }

    location / {
      proxy_pass http://alexwbt-ui:3000;
      proxy_intercept_errors on;
      error_page 404 = /index.html;
    }
  }
}
